// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jetefprstmoewdfhhwqq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpldGVmcHJzdG1vZXdkZmhod3FxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0NTcyMTUsImV4cCI6MjA2OTAzMzIxNX0.LB4B8Qx_oE1h1U3_Zu6FGyMGozbi0Hc7jia7Qa5TQW4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
}); 